name: Running Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    environment: ci-test

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn

      - name: migrate database
        run: yarn db:migrate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Run the mock tests function
        run: yarn test
